version: '3'

services:
  app:
    restart: always
    build: .
    command: npm start
    environment:
      - GIPHY_API_KEY=SpmIUSIToFAtbNjAg2x7UJwXRNOniFaC
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    networks:
      - api-network

  test:
    build: .
    image: app
    command: npm run test
    environment:
      - GIPHY_API_KEY=SpmIUSIToFAtbNjAg2x7UJwXRNOniFaC
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  node_modules:
